### ISSUE TITLE
Coleta de input do usuário na interface

### ISSUE THREAD

**Issue by gatotabaco** [UnBParadigmas2024-2/2024.2_G4_Funcional_CampoMinado#2]
Responsável: @gatotabaco 

Coleta o input do usuário (mouse)

- bool IsMouseButtonReleased(int button) para detectar se o houve click e release do mouse
- GetmouseX e getmouseY (raylib) para coletar as coordenadas a partir do momento que houve click
- converter o x e y para coordenadas na lista de listas

**Comment by yudi-azvd** [comment]
Resolvido com fc55305.
